// <auto-generated />
namespace ETrade.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0));
        
        string IMigrationMetadata.Id
        {
            get { return "202210080843599_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
